import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import AvatarImage from "@/../public/hachiware.jpg";
import AvatarImage2 from "@/../public/hachiware2.jpg";
import Link from "next/link";
import LinkImage1 from "@/app/image/house.png";
import HomeIcon from "@/app/image/icon_home.svg"
import GraduationIcon from "@/app/image/icon_graduation.svg"
import UiuxIcon from "@/app/image/icon_uiux.svg"
import P5jsIcon from "@/app/image/icon_p5js.svg"
import FacebookIcon from "@/app/image/icon_facebook.svg"
import InstagramIcon from "@/app/image/icon_instagram.svg"
import TwitterIcon from "@/app/image/icon_twitter.svg"
import ThreadIcon from "@/app/image/icon_thread.svg"
import CameraIcon from "@/app/image/icon_camera.svg"
import { Italiana } from 'next/font/google'
import Aurora from '@/component/Aurora';
import Iridescence from '@/component/Iridescence';
  

const italiana = Italiana({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "潘玉心的數位履歷",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${italiana.className} font-['Microsoft_JhengHei']`}
      >

      {/* <div className="absolute inset-0 -z-1 pointer-events-none">
        <Iridescence
          color={[0,0.6,0.7]}
          mouseReact={true}
          amplitude={0.1}
          speed={0.1}
        />
      </div> */}

      <div className="w-screen h-screen flex flex-col sm:flex-row gap-5 bg-[linear-gradient(to_bottom_right,_#00437B,_#AFC7D8)] p-8 box-border overflow-y-auto">
      {/* <div className="w-screen h-screen flex flex-col sm:flex-row gap-5 bg-transparent p-8 box-border overflow-y-auto"> */}

        {/* <div className="min-w-[320px] w-full sm:w-[320px] h-full rounded-2xl bg-[#D8E9F0] flex justify-start items-center flex-col p-[30px] pt-[80px] overflow-y-auto overflow-x-hidden"> */}
        <div className="min-w-[320px] w-full sm:w-[320px] h-full rounded-2xl bg-[#D8E9F0] flex justify-start items-center flex-col overflow-y-auto overflow-x-hidden">
          
          <div className="w-full bg-[#00437B] flex flex-col items-center rounded-b-[4vw]">
            <Image src={AvatarImage2} alt="Avatar" className="w-[80px] h-[80px] rounded-full mt-[64px]" />
            <h1 className="mt-2 text-white font-bold text-[18px]">潘玉心</h1>
            <p className="max-w-[380px] text-center text-white">
              心理系學生，斜槓數位內容。
            </p>

            {/* 社群連結 */}
            <div className="flex gap-4 my-10 mb-12">
              <a href="https://www.facebook.com/share/16KwfnLnzb/?mibextid=wwXIfr" target="_blank">
                <div className="bg-[linear-gradient(to_bottom_right,_#226390,_#A4C2D4)] w-[40px] h-[40px] rounded-full flex justify-center items-center transform transition duration-300 hover:scale-110">
                  <Image src={FacebookIcon} alt="Icon" className="w-[25px] h-[25px]" />
                </div>
              </a>
              <a href="https://www.instagram.com/yu_hsin_pan?igsh=MXhzdmc0cjg5dmEx&utm_source=qr" target="_blank">
                <div className="bg-[linear-gradient(to_bottom_right,_#226390,_#A4C2D4)] w-[40px] h-[40px] rounded-full flex justify-center items-center transform transition duration-300 hover:scale-110">
                  <Image src={InstagramIcon} alt="Icon" className="w-[23px] h-[23px]" />
                </div>
              </a>
              <a href="https://x.com/hanayo888?s=21&t=kCbnaUHtUNfSipeckNahZw" target="_blank">
                <div className="bg-[linear-gradient(to_bottom_right,_#226390,_#A4C2D4)] w-[40px] h-[40px] rounded-full flex justify-center items-center transform transition duration-300 hover:scale-110">
                  <Image src={TwitterIcon} alt="Icon" className="w-[21px] h-[21px]" />
                </div>
              </a>
              <a href="https://www.threads.net/@mallow_888?igshid=NTc4MTIwNjQ2YQ==" target="_blank">
                <div className="bg-[linear-gradient(to_bottom_right,_#226390,_#A4C2D4)] w-[40px] h-[40px] rounded-full flex justify-center items-center transform transition duration-300 hover:scale-110">
                  <Image src={ThreadIcon} alt="Icon" className="w-[24px] h-[24px]" />
                </div>
              </a>
            </div>
          </div>

          {/* <div className="">Information Categories</div> */}

          {/* 頁面切換 */}
          <div className="w-full flex-col flex gap-3 mt-6 px-10 text-[#00437B] font-bold">
            <div className="flex justify-center text-[20px]">Categories</div>
            
            <Link href="/">
              <div className="bg-[rgba(255,255,255,0.3)] w-full h-[70px] rounded-xl flex items-center p-2 border-4 border-transparent hover:border-white transition-all duration-300">
                <div className=" bg-[linear-gradient(to_bottom_right,_#008BBF,_#AAD2E4)] w-[40px] h-[40px] rounded-full mr-6 flex justify-center items-center">
                  <Image src={HomeIcon} alt="Icon" className="w-[23px] h-[23px]" />
                </div>
                <div>Home</div>
              </div>
            </Link>

            <Link href="/about">
              <div className="bg-[rgba(255,255,255,0.3)] w-full h-[70px] rounded-xl flex items-center p-2 border-4 border-transparent hover:border-white transition-all duration-300">
                <div className=" bg-[linear-gradient(to_bottom_right,_#008BBF,_#AAD2E4)] w-[40px] h-[40px] rounded-full mr-6 flex justify-center items-center">
                  <Image src={GraduationIcon} alt="Icon" className="w-[23px] h-[23px]" />
                </div>
                <div>About</div>
              </div>
            </Link>
{/* 
            <Link href="/uiux">
              <div className="bg-[rgba(255,255,255,0.3)] w-full h-[70px] rounded-xl flex items-center p-2 border-4 border-transparent hover:border-white transition-all duration-300">
                <div className=" bg-[linear-gradient(to_bottom_right,_#008BBF,_#AAD2E4)] w-[40px] h-[40px] rounded-full mr-6 flex justify-center items-center">
                  <Image src={UiuxIcon} alt="Icon" className="w-[23px] h-[23px]" />
                </div>
                <div>UI/UX</div>
              </div>
            </Link>

            <Link href="/p5js">
              <div className="bg-[rgba(255,255,255,0.3)] w-full h-[70px] rounded-xl flex items-center p-2 border-4 border-transparent hover:border-white transition-all duration-300">
                <div className="bg-[linear-gradient(to_bottom_right,_#008BBF,_#AAD2E4)] w-[40px] h-[40px] rounded-full mr-6 flex justify-center items-center">
                  <Image src={P5jsIcon} alt="Icon" className="w-[23px] h-[23px]" />
                </div>
                <div>P5.js</div>
              </div>
            </Link>

            <Link href="/photo">
              <div className="bg-[rgba(255,255,255,0.3)] w-full h-[70px] rounded-xl flex items-center p-2 border-4 border-transparent hover:border-white transition-all duration-300 mb-2">
                <div className="bg-[linear-gradient(to_bottom_right,_#008BBF,_#AAD2E4)] w-[40px] h-[40px] rounded-full mr-6 flex justify-center items-center">
                  <Image src={CameraIcon} alt="Icon" className="w-[23px] h-[23px]" />
                </div>
                <div>Photos</div>
              </div>
            </Link> */}

            <Link href="/project">
              <div className="bg-[rgba(255,255,255,0.3)] w-full h-[70px] rounded-xl flex items-center p-2 border-4 border-transparent hover:border-white transition-all duration-300">
                <div className="bg-[linear-gradient(to_bottom_right,_#008BBF,_#AAD2E4)] w-[40px] h-[40px] rounded-full mr-6 flex justify-center items-center">
                  <Image src={P5jsIcon} alt="Icon" className="w-[23px] h-[23px]" />
                </div>
                <div>Projects</div>
              </div>
            </Link>


          </div>
        </div>

        {children}

      </div>


      </body>
    </html>
  );
}
